### ISSUE TITLE
[11] You forgot 'vals' in def unlink

### ISSUE THREAD

**Issue by kopeyev** [muk-it/muk_base#11]
You have to add 'vals' to def unlink to avoid errors:
Should be '''def unlink(self, vals):''' instead of '''def unlink(self):'''.
No problem. Help me to solve issues in muk_web, please :)

**Comment by MathAndrews** [comment]
Hi,
I think I have the same issue in module "web_utils" in file ./models/res_groups.py
I think you might change `result = super(ResGroups, self).unlink(vals)` to `result = super(ResGroups, self).unlink()` in the `unlink` function, line 65

**Comment by keshrath** [comment]
I need more information: Which project? module? version? best is to send me a link to corresponding line (Github)

**Comment by MathAndrews** [comment]
For my comment: https://github.com/muk-it/muk_base/blob/70abc1c563f74d2c855e1380bebcc5f9268eae30/muk_utils/models/res_groups.py#L65

**Comment by keshrath** [comment]
https://github.com/muk-it/muk_base/commit/15d04061c823470670e0434778c1035ad2bd64f1
