### ISSUE TITLE
[11.0] module muk_converter added widget iap_credit_checker to res.config view, but this widget does not exist in 11.0

### ISSUE THREAD

**Issue by suvit** [muk-it/muk_base#17]
[11.0] module muk_converter added widget iap_credit_checker to res.config view, but this widget does not exist in 11.0

After enter to settings page, we got js-error ``Uncaught TypeError: Widget is not a constructor``

**Comment by katyukha** [comment]
I confirm this bug. It is present in current 11.0 branch.

**Comment by Kerrim-** [comment]
Hi I can't test it right now but does this resolve the issue? https://github.com/muk-it/muk_base/commit/25c41991e41acc9d5fad2303dba2ee86e63d29ef

**Comment by katyukha** [comment]
It seems that 25c4199 fixes this bug.
Thanks.
