### ISSUE TITLE
QWeb2 FieldMany2ManyTag 

### ISSUE THREAD

**Issue by hakon80** [muk-it/muk_base#2]
Hello,

when I just move muk_utils to my addons folder, without installing it or doing anything else, my Odoo is not working anymore, it just shows company logo nothing else.

Console says:
QWeb2: Can't clone undefined template FieldMany2ManyTag

Nothing special in log.
Using latest odoo 11 community edition on Linux.

Any idea what causes this problem?
After I delete muk_utils folder and reboot Odoo works fine again.
Muk DMS is working fine, but i want to install msoffice_preview.

Thanks

**Comment by keshrath** [comment]
This is really very strange the template FieldMany2ManyTag is not used in this module. Is there any information in the Odoo logs other than the error message in the console?

**Comment by hakon80** [comment]
On reboot I found now an error that muk_security is missing. I install it and now it works. I did not know at first it is requirement because it is not included in MuK Utils and does not say the requirement on Odoo Apps.
Thanks for answer and help.

**Comment by keshrath** [comment]
You are totally right. Thx for noticing it. :)

57e73049564062b2c00465cc14c137c5b3149bf1
