### ISSUE TITLE
Problem with v12 Not showing Branding and Avatar

### ISSUE THREAD

**Issue by luisvzqz** [muk-it/muk_base#22]
The problem happens in several installations of the muk theme, suddenly it stop showing the background and the avatar, without any reason, not evening upgrading the systems works.

Please see the attached files.
![AwesomeScreenshot-dev-360fin-mx-web-2019-08-12_8_52](https://user-images.githubusercontent.com/24595734/62910180-2acd4700-bd45-11e9-8d54-a6928639e7ea.png)
![AwesomeScreenshot-dev-360fin-mx-web-2019-08-12_8_52](https://user-images.githubusercontent.com/24595734/62910183-2d2fa100-bd45-11e9-8434-003b23a2174f.png)
![AwesomeScreenshot-dev-360fin-mx-web-2019-08-12_8_52 (1)](https://user-images.githubusercontent.com/24595734/62910189-30c32800-bd45-11e9-8608-8b760b0900ea.png)
![AwesomeScreenshot-dev-360fin-mx-web-2019-08-12_8_54](https://user-images.githubusercontent.com/24595734/62910191-328ceb80-bd45-11e9-8f5f-2b6a4fed10a5.png)
![Screen Shot 2019-08-12 at 21 04 40](https://user-images.githubusercontent.com/24595734/62910222-489aac00-bd45-11e9-9b06-6f32e7378808.png)
![Screen Shot 2019-08-12 at 21 00 38](https://user-images.githubusercontent.com/24595734/62910223-489aac00-bd45-11e9-93df-4b4b9f355258.png)

**Comment by keshrath** [comment]
Take a look at your browser console while you are in debug mode with assets. Are there any errors? Check the network panel as well.
