### ISSUE TITLE
[11.0] Error on delete groups

### ISSUE THREAD

**Issue by yastri** [muk-it/muk_base#8]
File "/opt/odoo/addons-custom/muk-it/muk_base/muk_utils/models/res_groups.py", line 65, in unlink
    result = super(ResGroups, self).unlink(vals)
NameError: name 'vals' is not defined

**Comment by keshrath** [comment]
https://github.com/muk-it/muk_base/commit/c46eb91926ec15c773ca5f42318e39de75c6100b
